apiVersion: v1
kind: Secret
metadata:
  name: {{ include "notification.fullname" . }}-secrets
type: Opaque
data:
  appUsername: {{.Values.notification.postgres.appUsername|b64enc}}      #b3R1c3VzZXI= #otususer
  appPassword: {{.Values.notification.postgres.appPassword|b64enc}}  #b3R1c3VzZXI= #otususer
  appDbUrl: {{.Values.notification.postgres.appDbUrl|b64enc}}        #amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXMtc2VydmljZTo1NDMyL290dXNkYg== #jdbc:postgresql://postgres-service:5432/otusdb
  rabbitmqUsername: {{.Values.notification.rabbitmq.username|b64enc}} 
  rabbitmqPassword: {{.Values.notification.rabbitmq.password|b64enc}} 


     