{{- if .Values.payment.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "payment.fullname" . }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    {{- range .Values.payment.ingress.rules }}
  - host: {{ .host }}
    http:
      paths:
      {{- range .http.paths }}
      - path: {{ .path }}
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ include "payment.fullname" (dict "Values" $.Values "Release" $.Release "Path" . ) }}-service
            port:
              number: {{ .service.port }}
      {{- end }}
    {{- end }}
  ingressClassName: nginx
{{- end }}
