apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "auth.fullname" . }}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "auth.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "auth.fullname" . }}
    spec:
      containers: 
        - name: {{ include "auth.fullname" . }}-app
          image: aboldyrev1111/otus-homework-d-auth:4.0
          #env
          env:
          - name: POSTGRES_APP_USER
            valueFrom:
              secretKeyRef:
                name: {{ include "auth.fullname" . }}-secrets
                key: appUsername
          - name: POSTGRES_APP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "auth.fullname" . }}-secrets
                key: appPassword
          - name: POSTGRES_URL
            valueFrom:
              secretKeyRef:
                name: {{ include "auth.fullname" . }}-secrets
                key: appDbUrl
          - name: RABBITMQ_USER
            valueFrom:
              secretKeyRef:
                name: {{ include "auth.fullname" . }}-secrets
                key: rabbitmqUsername
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "auth.fullname" . }}-secrets
                key: rabbitmqPassword
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "auth.fullname" . }}-secrets
                key: redisPassword
          #volumeMounts
          volumeMounts:
          - name: {{ include "auth.fullname" . }}-configmap
            mountPath: /opt/otus-homework/config
          #livenessProbe
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: web
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 5
          #readinessProbe
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: web
            initialDelaySeconds: 30
            periodSeconds: 5 
          #ports
          ports:
          - name: web
            containerPort: {{.Values.auth.service.port}}              
            protocol: TCP
      volumes:
        - name: {{ include "auth.fullname" . }}-configmap
          configMap:
            name: {{ include "auth.fullname" . }}-configmap                  