apiVersion: v1
kind: ConfigMap
metadata: 
  name: {{ include "auth.fullname" . }}-configmap
data:
  application.yml: |
    server:
      port: {{.Values.auth.service.port}}
      shutdown: graceful
    spring:
      redis:
        host: {{.Values.redis.host}}
        port: {{.Values.redis.port}}
        password: ${REDIS_PASSWORD}
      rabbitmq:
        host: {{.Values.rabbitmq.service}}
        port: {{.Values.rabbitmq.port}}
        username: ${RABBITMQ_USER}
        password: ${RABBITMQ_PASSWORD}
      datasource:
        url: ${POSTGRES_URL}
        username: ${POSTGRES_APP_USER}
        password: ${POSTGRES_APP_PASSWORD}
        driver-class-name: org.postgresql.Driver
      jpa:
        hibernate:
          ddl-auto: update
      mvc:
        pathmatch:
          matching-strategy: ant_path_matcher
    springfox:
      documentation:
        swagger-ui:
          base-url: /auth-doc
        swagger:
          v2:
            path: /auth-doc/v2/api-docs
    management:
      endpoint:
        metrics:
          enabled: true
      endpoints:
        web:
          exposure:
            include: health, info, prometheus
      metrics:
        export:
          prometheus:
            enabled: true  
    application:
      redis:
        session-ttl: {{.Values.auth.redis.sessionTtl}}
      role: {{.Values.auth.name}}
      rabbitmq:
        account:
          exchangeName: {{.Values.rabbitmq.account.exchangeName}}
        notification:
          exchangeName: {{.Values.rabbitmq.notification.exchangeName}}

