apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: payment-monitor
  # Change this to the namespace the Prometheus instance is running in
  # namespace: default
  labels:
    app: payment
    team: otus
spec:
  selector:
    matchLabels:
      app: payment # target gitlab service
  endpoints:
  - port: web   
    path: /actuator/prometheus
    interval: 15s