apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rabbitmq.fullname" . }}
type: Opaque
data:
  username: {{ .Values.rabbitmq.username | b64enc | quote }}
  password: {{ .Values.rabbitmq.password | b64enc | quote }}