apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  labels:
    app: {{ include "rabbitmq.name" . }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.rabbitmq.port }}
      targetPort: {{ .Values.rabbitmq.port }}
      protocol: TCP
      name: amqp
    - port: {{ .Values.rabbitmq.uiPort }}
      targetPort: {{ .Values.rabbitmq.uiPort }}
      protocol: TCP
      name: management
    - port: {{ .Values.rabbitmq.metricsPort }}
      targetPort: {{ .Values.rabbitmq.metricsPort }}
      protocol: TCP
      name: metrics
  selector:
    app: {{ include "rabbitmq.name" . }}