apiVersion: v1
kind: ConfigMap
metadata: 
  name: crud-configmap
data:
  application.yml: |
    server:
      port: '8000'
      shutdown: graceful
    spring:
      datasource:
        url: 'jdbc:postgresql://localhost:5432/otususerdb'
        username: 'otususer'
        password: 'otususer123'
        driver-class-name: org.postgresql.Driver
      jpa:
        hibernate:
          ddl-auto: update
